### ISSUE TITLE
Add a page for adding and editing Stats

### ISSUE THREAD

**Issue by icco** [icco/graphql#2]
There is a stat object and like posts should be able to be edited in the web UI.

 - The Stat struct: https://github.com/icco/graphql/blob/master/models_gen.go#L48-L52 (can be moved into a new file called `stat.go`)
 - The Post handlers as example: https://github.com/icco/graphql/blob/master/server/admin.go#L30-L73

**Comment by mukulrawat1986** [comment]
Hi, I would love to work on this issue, may I attempt this?

**Comment by icco** [comment]
Totally! Let me know if you have any questions @mukulrawat1986. I'm updating the readme as we speak to be a little better on how to get the app running.

**Comment by mukulrawat1986** [comment]
Thank you .

**Comment by mukulrawat1986** [comment]
Hey, I am working on another issue right now and will later set the repo up on my system. I will start working on this issue tomorrow morning (its night here). I want to get better at writing web applications and working with databases, that's why I am interested in this, but most of my experience working with Go involves making command line tools, so I will be a bit slow at the beginning picking this up, hope that is cool with you.

**Comment by icco** [comment]
Definitely! I'm in no rush.

**Comment by icco** [comment]
How's it going @mukulrawat1986 ? Any questions?
